config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
resources :trabajadores_lists do
	resources :trabajadores_items
  	resources :tlc_lists
  	resources :tlcp_rueba_lists
  	resources :todo_lists
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "trabajadores_lists#index"

end

app/models/tlcp_rueba_list.rb
class TlcpRuebaList < ApplicationRecord
end

app/controllers/tlcp_rueba_lists_controller.rb
class TlcpRuebaListsController < ApplicationController
  before_action :set_tlcp_rueba_list, only: [:show, :edit, :update, :destroy]

  # GET /tlcp_rueba_lists
  # GET /tlcp_rueba_lists.json
  def index
    @tlcp_rueba_lists = TlcpRuebaList.all
  end

  # GET /tlcp_rueba_lists/1
  # GET /tlcp_rueba_lists/1.json
  def show
  end

  # GET /tlcp_rueba_lists/new
  def new
    @tlcp_rueba_list = TlcpRuebaList.new
  end

  # GET /tlcp_rueba_lists/1/edit
  def edit
  end

  # POST /tlcp_rueba_lists
  # POST /tlcp_rueba_lists.json
  def create
    @tlcp_rueba_list = TlcpRuebaList.new(tlcp_rueba_list_params)

    respond_to do |format|
      if @tlcp_rueba_list.save
        format.html { redirect_to @tlcp_rueba_list, notice: 'Tlcp rueba list was successfully created.' }
        format.json { render :show, status: :created, location: @tlcp_rueba_list }
      else
        format.html { render :new }
        format.json { render json: @tlcp_rueba_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tlcp_rueba_lists/1
  # PATCH/PUT /tlcp_rueba_lists/1.json
  def update
    respond_to do |format|
      if @tlcp_rueba_list.update(tlcp_rueba_list_params)
        format.html { redirect_to @tlcp_rueba_list, notice: 'Tlcp rueba list was successfully updated.' }
        format.json { render :show, status: :ok, location: @tlcp_rueba_list }
      else
        format.html { render :edit }
        format.json { render json: @tlcp_rueba_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tlcp_rueba_lists/1
  # DELETE /tlcp_rueba_lists/1.json
  def destroy
    @tlcp_rueba_list.destroy
    respond_to do |format|
      format.html { redirect_to tlcp_rueba_lists_url, notice: 'Tlcp rueba list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tlcp_rueba_list
      @tlcp_rueba_list = TlcpRuebaList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tlcp_rueba_list_params
      params.require(:tlcp_rueba_list).permit(:title, :description)
    end
end

app/helpers/tlcp_rueba_lists_helper.rb
module TlcpRuebaListsHelper
end

app/views/tlcp_rueba_lists/_form.html.erb
<%= form_with(model: tlcp_rueba_list, local: true) do |form| %>
  <% if tlcp_rueba_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tlcp_rueba_list.errors.count, "error") %> prohibited this tlcp_rueba_list from being saved:</h2>

      <ul>
      <% tlcp_rueba_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tlcp_rueba_lists/edit.html.erb
<h1>Editing Tlcp Rueba List</h1>

<%= render 'form', tlcp_rueba_list: @tlcp_rueba_list %>

<%= link_to 'Show', @tlcp_rueba_list %> |
<%= link_to 'Back', tlcp_rueba_lists_path %>

app/views/tlcp_rueba_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tlcp Rueba Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tlcp_rueba_lists.each do |tlcp_rueba_list| %>
      <tr>
        <td><%= tlcp_rueba_list.title %></td>
        <td><%= tlcp_rueba_list.description %></td>
        <td><%= link_to 'Show', tlcp_rueba_list %></td>
        <td><%= link_to 'Edit', edit_tlcp_rueba_list_path(tlcp_rueba_list) %></td>
        <td><%= link_to 'Destroy', tlcp_rueba_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tlcp Rueba List', new_tlcp_rueba_list_path %>

app/views/tlcp_rueba_lists/new.html.erb
<h1>New Tlcp Rueba List</h1>

<%= render 'form', tlcp_rueba_list: @tlcp_rueba_list %>

<%= link_to 'Back', tlcp_rueba_lists_path %>

app/views/tlcp_rueba_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tlcp_rueba_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tlcp_rueba_list.description %>
</p>

<%= link_to 'Edit', edit_tlcp_rueba_list_path(@tlcp_rueba_list) %> |
<%= link_to 'Back', tlcp_rueba_lists_path %>