config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
resources :trabajadores_lists do
	resources :trabajadores_items
  	resources :tlc_lists
  	resources :tlcp_rueba_lists
  	resources :todo_lists
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "trabajadores_lists#index"

end

app/models/tlc_list.rb
class TlcList < ApplicationRecord
end

app/controllers/tlc_lists_controller.rb
class TlcListsController < ApplicationController
  before_action :set_tlc_list, only: [:show, :edit, :update, :destroy]

  # GET /tlc_lists
  # GET /tlc_lists.json
  def index
    @tlc_lists = TlcList.all
  end

  # GET /tlc_lists/1
  # GET /tlc_lists/1.json
  def show
  end

  # GET /tlc_lists/new
  def new
    @tlc_list = TlcList.new
  end

  # GET /tlc_lists/1/edit
  def edit
  end

  # POST /tlc_lists
  # POST /tlc_lists.json
  def create
    @tlc_list = TlcList.new(tlc_list_params)

    respond_to do |format|
      if @tlc_list.save
        format.html { redirect_to @tlc_list, notice: 'Tlc list was successfully created.' }
        format.json { render :show, status: :created, location: @tlc_list }
      else
        format.html { render :new }
        format.json { render json: @tlc_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tlc_lists/1
  # PATCH/PUT /tlc_lists/1.json
  def update
    respond_to do |format|
      if @tlc_list.update(tlc_list_params)
        format.html { redirect_to @tlc_list, notice: 'Tlc list was successfully updated.' }
        format.json { render :show, status: :ok, location: @tlc_list }
      else
        format.html { render :edit }
        format.json { render json: @tlc_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tlc_lists/1
  # DELETE /tlc_lists/1.json
  def destroy
    @tlc_list.destroy
    respond_to do |format|
      format.html { redirect_to tlc_lists_url, notice: 'Tlc list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tlc_list
      @tlc_list = TlcList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tlc_list_params
      params.require(:tlc_list).permit(:title, :description)
    end
end

app/helpers/tlc_lists_helper.rb
module TlcListsHelper
end

app/views/tlc_lists/_form.html.erb
<%= form_with(model: tlc_list, local: true) do |form| %>
  <% if tlc_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tlc_list.errors.count, "error") %> prohibited this tlc_list from being saved:</h2>

      <ul>
      <% tlc_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tlc_lists/edit.html.erb
<h1>Editing Tlc List</h1>

<%= render 'form', tlc_list: @tlc_list %>

<%= link_to 'Show', @tlc_list %> |
<%= link_to 'Back', tlc_lists_path %>

app/views/tlc_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tlc Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tlc_lists.each do |tlc_list| %>
      <tr>
        <td><%= tlc_list.title %></td>
        <td><%= tlc_list.description %></td>
        <td><%= link_to 'Show', tlc_list %></td>
        <td><%= link_to 'Edit', edit_tlc_list_path(tlc_list) %></td>
        <td><%= link_to 'Destroy', tlc_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tlc List', new_tlc_list_path %>

app/views/tlc_lists/new.html.erb
<h1>New Tlc List</h1>

<%= render 'form', tlc_list: @tlc_list %>

<%= link_to 'Back', tlc_lists_path %>

app/views/tlc_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tlc_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tlc_list.description %>
</p>

<%= link_to 'Edit', edit_tlc_list_path(@tlc_list) %> |
<%= link_to 'Back', tlc_lists_path %>