config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
resources :trabajadores_lists do
	resources :trabajadores_items
  	resources :tlc_lists
  	resources :tlcp_rueba_lists
  	resources :todo_lists
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "trabajadores_lists#index"

end

app/models/trabajadores_list.rb
class TrabajadoresList < ApplicationRecord
	has_many :trabajadores_items
end

app/controllers/trabajadores_lists_controller.rb
class TrabajadoresListsController < ApplicationController
  before_action :set_trabajadores_list, only: [:show, :edit, :update, :destroy]

  # GET /trabajadores_lists
  # GET /trabajadores_lists.json
  def index
    @trabajadores_lists = TrabajadoresList.all
  end

  # GET /trabajadores_lists/1
  # GET /trabajadores_lists/1.json
  def show
  end

  # GET /trabajadores_lists/new
  def new
    @trabajadores_list = TrabajadoresList.new
  end

  # GET /trabajadores_lists/1/edit
  def edit
  end

  # POST /trabajadores_lists
  # POST /trabajadores_lists.json
  def create
    @trabajadores_list = TrabajadoresList.new(trabajadores_list_params)

    respond_to do |format|
      if @trabajadores_list.save
        format.html { redirect_to @trabajadores_list, notice: 'Trabajadores list was successfully created.' }
        format.json { render :show, status: :created, location: @trabajadores_list }
      else
        format.html { render :new }
        format.json { render json: @trabajadores_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabajadores_lists/1
  # PATCH/PUT /trabajadores_lists/1.json
  def update
    respond_to do |format|
      if @trabajadores_list.update(trabajadores_list_params)
        format.html { redirect_to @trabajadores_list, notice: 'Trabajadores list was successfully updated.' }
        format.json { render :show, status: :ok, location: @trabajadores_list }
      else
        format.html { render :edit }
        format.json { render json: @trabajadores_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabajadores_lists/1
  # DELETE /trabajadores_lists/1.json
  def destroy
    @trabajadores_list.destroy
    respond_to do |format|
      format.html { redirect_to trabajadores_lists_url, notice: 'Trabajadores list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajadores_list
      @trabajadores_list = TrabajadoresList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trabajadores_list_params
      params.require(:trabajadores_list).permit(:Nombres, :Apellidos)
    end
end

app/helpers/trabajadores_lists_helper.rb
module TrabajadoresListsHelper
end

app/views/trabajadores_lists/_form.html.erb
<%= form_with(model: trabajadores_list, local: true) do |form| %>
  <% if trabajadores_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trabajadores_list.errors.count, "error") %> prohibited this trabajadores_list from being saved:</h2>

      <ul>
      <% trabajadores_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombres %>
    <%= form.text_field :Nombres %>
  </div>

  <div class="field">
    <%= form.label :Apellidos %>
    <%= form.text_area :Apellidos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trabajadores_lists/edit.html.erb
<h1>Editing Trabajadores List</h1>

<%= render 'form', trabajadores_list: @trabajadores_list %>

<%= link_to 'Show', @trabajadores_list %> |
<%= link_to 'Back', trabajadores_lists_path %>

app/views/trabajadores_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trabajadores Lists</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trabajadores_lists.each do |trabajadores_list| %>
      <tr>
        <td><%= trabajadores_list.Nombres %></td>
        <td><%= trabajadores_list.Apellidos %></td>
        <td><%= link_to 'Show', trabajadores_list %></td>
        <td><%= link_to 'Edit', edit_trabajadores_list_path(trabajadores_list) %></td>
        <td><%= link_to 'Destroy', trabajadores_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trabajadores List', new_trabajadores_list_path %>

app/views/trabajadores_lists/new.html.erb
<h1>New Trabajadores List</h1>

<%= render 'form', trabajadores_list: @trabajadores_list %>

<%= link_to 'Back', trabajadores_lists_path %>

app/views/trabajadores_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @trabajadores_list.Nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @trabajadores_list.Apellidos %>
</p>

<div id="trabajadores_items_wrapper">
 <%= render @trabajadores_list.trabajadores_items %>
 
 <div id="form">
  		<%= render "trabajadores_items/form" %>
 </div>
</div>

<%= link_to 'Edit', edit_trabajadores_list_path(@trabajadores_list) %> |
<%= link_to 'Back', trabajadores_lists_path %>